name: ServerBroadcast
version: 1.0
main: com.iain.arcwood.Main
api-version: 1.14
commands:
  rmb:
    description: change the amount of time between messages in seconds or minutes.
    permission: arcwood.rmb
    usage: /rmb [Number] [minutes or seconds (M/S)] 